// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmoCE5eYH0QzOxIUAvZNMFMa_BzaCHh7A',
    appId: '1:346325927506:web:8821ec5a9be3623a98418b',
    messagingSenderId: '346325927506',
    projectId: 'remedia-714aa',
    authDomain: 'remedia-714aa.firebaseapp.com',
    storageBucket: 'remedia-714aa.firebasestorage.app',
    measurementId: 'G-PY6QL5SH66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5aAU3irL7vZ4EHnYF16ghOr96dWc06RY',
    appId: '1:346325927506:android:d6c53bba18c2b6fc98418b',
    messagingSenderId: '346325927506',
    projectId: 'remedia-714aa',
    storageBucket: 'remedia-714aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4MYbyeZIXI1ZpzqVSjl00kjd7M8tvSlU',
    appId: '1:346325927506:ios:9a068f687660021798418b',
    messagingSenderId: '346325927506',
    projectId: 'remedia-714aa',
    storageBucket: 'remedia-714aa.firebasestorage.app',
    iosBundleId: 'com.example.remedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4MYbyeZIXI1ZpzqVSjl00kjd7M8tvSlU',
    appId: '1:346325927506:ios:9a068f687660021798418b',
    messagingSenderId: '346325927506',
    projectId: 'remedia-714aa',
    storageBucket: 'remedia-714aa.firebasestorage.app',
    iosBundleId: 'com.example.remedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmoCE5eYH0QzOxIUAvZNMFMa_BzaCHh7A',
    appId: '1:346325927506:web:e4ff734909217b5298418b',
    messagingSenderId: '346325927506',
    projectId: 'remedia-714aa',
    authDomain: 'remedia-714aa.firebaseapp.com',
    storageBucket: 'remedia-714aa.firebasestorage.app',
    measurementId: 'G-FHZRCD1S3B',
  );
}
